server:
  port: 10010
spring:
  application:
    name: cloud-system
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        watch-delay: 1000
        server-addr: 127.0.0.1:8848
  datasource: # 7 : 设置数据库配置
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.94.224.61:3306/qs?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: quansu123
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    # 连接池配置
    druid:
      initialSize: 2
      minIdle: 2
      maxActive: 30
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      serialization:
        write-dates-as-timestamps: false


#启用 httpclient
feign:
  httpclient:
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
        connectTimeout: 5000  #连接超时时间
        readTimeout: 50000    #连接超时时间
