server:
  port: 10010
spring:
  application:
    name: cloud-system
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        watch-delay: 1000
        server-addr: 127.0.0.1:8848
    sentinel:  # 10 sentinel 配置
      transport:
        dashboard: localhost:8858 #配置sentinel dashboard地址
        port: 8719
      datasource: # 10.1 将sentinel规则持久化到nacos中
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
    stream: # 9 :RocketMq 配置
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        output:
          destination: mq-topic
        input:
          destination: mq-topic
          group: mq-group
  datasource: # 7 : 设置数据库配置
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/cloud-sys?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    # 连接池配置
    druid:
      initialSize: 2
      minIdle: 2
      maxActive: 30
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      serialization:
        write-dates-as-timestamps: false
#启用 httpclient
feign:
  httpclient:
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
        connectTimeout: 5000  #连接超时时间
        readTimeout: 50000    #连接超时时间
  sentinel:
    enabled: true # 10.2 打开sentinel对feign的支持

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xf.cloud.cloudsystem.entity
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
