server:
  port: 10020
spring:
  application:
    name: cloud-base
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        watch-delay: 1000
        server-addr: 127.0.0.1:8848
#启用 httpclient
feign:
  httpclient:
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
        connectTimeout: 5000  #连接超时时间
        readTimeout: 50000    #连接超时时间